name: 'build-api'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and install NPM packages
        uses: ./.github/actions/setup

      - name: Build API
        run: cd ./apps/web && npm run build